blank_issues_enabled: true
contact_links:
    - name: Feature Request
      url: https://github.com/spatie/laravel-db-snapshots/discussions/new?category=ideas
      about: Share ideas for new features
    - name: Ask a Question
      url: https://github.com/spatie/laravel-db-snapshots/discussions/new?category=q-a
      about: Ask the community for help
